// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/realworld/v1/account.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account []*AccountsReply_Account `protobuf:"bytes,1,rep,name=account,proto3" json:"account,omitempty"`
}

func (x *AccountsReply) Reset() {
	*x = AccountsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_realworld_v1_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsReply) ProtoMessage() {}

func (x *AccountsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_realworld_v1_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsReply.ProtoReflect.Descriptor instead.
func (*AccountsReply) Descriptor() ([]byte, []int) {
	return file_api_realworld_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountsReply) GetAccount() []*AccountsReply_Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type AccountsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit *int32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
}

func (x *AccountsRequest) Reset() {
	*x = AccountsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_realworld_v1_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsRequest) ProtoMessage() {}

func (x *AccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_realworld_v1_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsRequest.ProtoReflect.Descriptor instead.
func (*AccountsRequest) Descriptor() ([]byte, []int) {
	return file_api_realworld_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type AccountsReply_Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Uid     int32  `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Type    int32  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Balance string `protobuf:"bytes,4,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Tag     string `protobuf:"bytes,5,opt,name=Tag,proto3" json:"Tag,omitempty"`
	DT      string `protobuf:"bytes,6,opt,name=DT,proto3" json:"DT,omitempty"`
	Ctime   string `protobuf:"bytes,7,opt,name=ctime,proto3" json:"ctime,omitempty"`
}

func (x *AccountsReply_Account) Reset() {
	*x = AccountsReply_Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_realworld_v1_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountsReply_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsReply_Account) ProtoMessage() {}

func (x *AccountsReply_Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_realworld_v1_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsReply_Account.ProtoReflect.Descriptor instead.
func (*AccountsReply_Account) Descriptor() ([]byte, []int) {
	return file_api_realworld_v1_account_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AccountsReply_Account) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AccountsReply_Account) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AccountsReply_Account) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AccountsReply_Account) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *AccountsReply_Account) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AccountsReply_Account) GetDT() string {
	if x != nil {
		return x.DT
	}
	return ""
}

func (x *AccountsReply_Account) GetCtime() string {
	if x != nil {
		return x.Ctime
	}
	return ""
}

var File_api_realworld_v1_account_proto protoreflect.FileDescriptor

var file_api_realworld_v1_account_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x61, 0x6c, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe0, 0x01, 0x0a, 0x0d, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x91, 0x01, 0x0a, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x44, 0x54, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x44, 0x54, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a,
	0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x32, 0x64, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x59, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x1b, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x65, 0x6e, 0x63, 0x77,
	0x2f, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2d, 0x72, 0x65, 0x61, 0x6c, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_realworld_v1_account_proto_rawDescOnce sync.Once
	file_api_realworld_v1_account_proto_rawDescData = file_api_realworld_v1_account_proto_rawDesc
)

func file_api_realworld_v1_account_proto_rawDescGZIP() []byte {
	file_api_realworld_v1_account_proto_rawDescOnce.Do(func() {
		file_api_realworld_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_realworld_v1_account_proto_rawDescData)
	})
	return file_api_realworld_v1_account_proto_rawDescData
}

var file_api_realworld_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_realworld_v1_account_proto_goTypes = []interface{}{
	(*AccountsReply)(nil),         // 0: account.v1.AccountsReply
	(*AccountsRequest)(nil),       // 1: account.v1.AccountsRequest
	(*AccountsReply_Account)(nil), // 2: account.v1.AccountsReply.Account
}
var file_api_realworld_v1_account_proto_depIdxs = []int32{
	2, // 0: account.v1.AccountsReply.account:type_name -> account.v1.AccountsReply.Account
	1, // 1: account.v1.Account.Accounts:input_type -> account.v1.AccountsRequest
	0, // 2: account.v1.Account.Accounts:output_type -> account.v1.AccountsReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_realworld_v1_account_proto_init() }
func file_api_realworld_v1_account_proto_init() {
	if File_api_realworld_v1_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_realworld_v1_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_realworld_v1_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_realworld_v1_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountsReply_Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_realworld_v1_account_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_realworld_v1_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_realworld_v1_account_proto_goTypes,
		DependencyIndexes: file_api_realworld_v1_account_proto_depIdxs,
		MessageInfos:      file_api_realworld_v1_account_proto_msgTypes,
	}.Build()
	File_api_realworld_v1_account_proto = out.File
	file_api_realworld_v1_account_proto_rawDesc = nil
	file_api_realworld_v1_account_proto_goTypes = nil
	file_api_realworld_v1_account_proto_depIdxs = nil
}
