// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/shencw/kratos-realworld/internal/biz"
	"github.com/shencw/kratos-realworld/internal/conf"
	"github.com/shencw/kratos-realworld/internal/data"
	"github.com/shencw/kratos-realworld/internal/server"
	"github.com/shencw/kratos-realworld/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewRealWorldDB(confServer, confData, logger)
	client := data.NewRedisConn(confData, logger)
	connection := data.NewHiveConn(confData, logger)
	saramaClient := data.NewKafkaClient(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, connection, saramaClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewAuthRepo(dataData, logger)
	authUseCase := biz.NewAuthUseCase(userRepo, logger)
	realWorldService := service.NewRealWorldService(authUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, realWorldService, logger)
	grpcServer := server.NewGRPCServer(confServer, realWorldService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
